### PR TITLE
feat: Coverage summary prototypes COV-9

### PR DESCRIPTION
**Pull request by prcr**
This is a dummy pull request to test out different prototypes of the coverage summary comment.

For more context see [COV-9](https://codacy.atlassian.net/browse/COV-9).

### CODE REVIEW

**Comment by prcr** [comment]
## Coverage summary from Codacy

Merging #8 (3bca793) into `main` (63c3f4a) - [See PR on Codacy](#)

### Coverage variation[^1]

| | Coverable lines | Covered lines | Coverage |
| ------------- | ------------- | ------------- | ------------- |
| Common ancestor commit (63c3f4a) | 5045 | 2521 | 49.97% |
| Head commit (3bca793) | 5056 | 2531 | 50.06% |
| **Variation** | 11 | 10 | **0.90% :heavy_check_mark: (1% target)** |

### Diff coverage[^2]

| Coverable lines | Covered lines | Diff coverage |
| ------------- | ------------- | ------------- |
| 20 | 11 | **55.00% :x: (60% target)** |

### [See your coverage quality gates (targets)](#) [Change summary preferences](#)

[^1]: **Coverage variation:** variation of the coverage value between the head commit and common ancestor commit of the pull request branch (`<coverage of head commit> - <coverage of common ancestor commit>`).
[^2]: **Diff coverage:** percentage of lines that are covered by tests out of the coverable lines that the pull request added or modified (`<covered lines added or modified>/<coverable lines added or modified> * 100%`).

**Comment by prcr** [comment]
## Coverage summary from Codacy

Merging #12 (40d85d7) into `main` (63c3f4a) - [See PR on Codacy](#)

| Coverage variation | Diff coverage |
| ------------- | ------------- |
| **0.90%** :heavy_check_mark: (1% target) | **55.00%** :x: (60% target) |

### Coverage variation details[^1]

| | Coverable lines | Covered lines | Coverage |
| ------------- | ------------- | ------------- | ------------- |
| Common ancestor commit (63c3f4a) | 5045 | 2521 | 49.97% |
| Head commit (40d85d7) | 5056 | 2531 | 50.06% |
| **Variation** | 11 | 10 | **0.90%** |



### Diff coverage details[^2]

| Coverable lines | Covered lines | Diff coverage |
| ------------- | ------------- | ------------- |
| 20 | 11 | **55.00%** |

#### [See your quality gate settings](#)&nbsp;&nbsp;&nbsp;&nbsp;[Change summary preferences](#)

[^1]: **Coverage variation** is the difference between the coverage for the head and common ancestor commits of the pull request branch: `<coverage of head commit> - <coverage of common ancestor commit>`

[^2]: **Diff coverage** is the percentage of lines that are covered by tests out of the coverable lines that the pull request added or modified: `<covered lines added or modified>/<coverable lines added or modified> * 100%`

**Comment by prcr** [comment]
## Coverage summary from Codacy

Merging #12 (40d85d7) into `main` (63c3f4a) - [See PR on Codacy](#)

| Coverage variation | Diff coverage |
| ------------- | ------------- |
| **0.90%** :heavy_check_mark: (1% target) | **55.00%** :x: (60% target) |

### Coverage variation details[^1]

| | Coverable lines | Covered lines | Coverage |
| ------------- | ------------- | ------------- | ------------- |
| Common ancestor commit (63c3f4a) | 5045 | 2521 | 49.97% |
| Head commit (40d85d7) | 5056 | 2531 | 50.06% |
| **Variation** | 11 | 10 | **0.90%** |

### Diff coverage details[^2]

| Coverable lines | Covered lines | Diff coverage |
| ------------- | ------------- | ------------- |
| 20 | 11 | **55.00%** |

#### [See your quality gate settings](#)&nbsp;&nbsp;&nbsp;&nbsp;[Change summary preferences](#)

[^1]: **Coverage variation** is the difference between the coverage for the head and common ancestor commits of the pull request branch: `<coverage of head commit> - <coverage of common ancestor commit>`
[^2]: **Diff coverage** is the percentage of lines that are covered by tests out of the coverable lines that the pull request added or modified: `<covered lines added or modified>/<coverable lines added or modified> * 100%`

**Comment by prcr** [comment]
_Coverage missing for **common ancestor commit only**_

## Coverage summary from Codacy

Merging #12 (40d85d7) into `main` (63c3f4a) - [See PR on Codacy](#)

| Coverage variation | Diff coverage |
| ------------- | ------------- |
| :x: **[Check your coverage integration](https://app.codacy.com/gh/codacy-docs/sandbox/settings/coverage)** (1% target) | :x: **55.00%** (60% target) |

### Coverage variation details[^1]

| | Coverable lines | Covered lines | Coverage |
| ------------- | ------------- | ------------- | ------------- |
| Common ancestor commit (63c3f4a) | - | - | [Check your coverage integration](https://app.codacy.com/gh/codacy-docs/sandbox/settings/coverage) |
| Head commit (40d85d7) | 5056 (-) | 2531 (-) | 50.06% (**-**) |

### Diff coverage details[^2]

| | Coverable lines | Covered lines | Diff coverage |
| ------------- | ------------- | ------------- | ------------- |
|Pull request (#12) | 20 | 11 | **55.00%** |

#### [See your quality gate settings](#)&nbsp;&nbsp;&nbsp;&nbsp;[Change summary preferences](#)

[^1]: **Coverage variation** is the difference between the coverage for the head and common ancestor commits of the pull request branch: `<coverage of head commit> - <coverage of common ancestor commit>`
[^2]: **Diff coverage** is the percentage of lines that are covered by tests out of the coverable lines that the pull request added or modified: `<covered lines added or modified>/<coverable lines added or modified> * 100%`

**Comment by prcr** [comment]
_When diff coverage is "not applicable"_

## Coverage summary from Codacy

Merging #12 (40d85d7) into `main` (63c3f4a) - [See PR on Codacy](https://app.codacy.com/gh/codacy-docs/sandbox/pullRequest?prid=10710600)

| Coverage variation | Diff coverage |
| ------------- | ------------- |
| :heavy_check_mark: **0.90%** (1% target) | :x: **55.00%** (60% target) |

### Coverage variation details[^1]

| | Coverable lines | Covered lines | Coverage |
| ------------- | ------------- | ------------- | ------------- |
| Common ancestor commit (63c3f4a) | 5045 | 2521 | 49.97% |
| Head commit (40d85d7) | 5056 (+11) | 2531 (+10) | 50.06% (**+0.90%**) |

### Diff coverage details[^2]

| | Coverable lines | Covered lines | Diff coverage |
| ------------- | ------------- | ------------- | ------------- |
|Pull request (#12) | 20 | 11 | **55.00%** |

#### [See your quality gate settings](https://app.codacy.com/gh/codacy-docs/sandbox/settings/quality)&nbsp;&nbsp;&nbsp;&nbsp;[Change summary preferences](https://app.codacy.com/gh/codacy-docs/sandbox/settings/integrations)

[^1]: **Coverage variation** is the difference between the coverage for the head and common ancestor commits of the pull request branch: `<coverage of head commit> - <coverage of common ancestor commit>`
[^2]: **Diff coverage** is the percentage of lines that are covered by tests out of the coverable lines that the pull request added or modified: `<covered lines added or modified>/<coverable lines added or modified> * 100%`

**Comment by fjrdomingues** [comment]
🟢 🔴

**Comment by prcr** [comment]
- Check emojis, must be green
- Have explicit + and - signs on all values
- Coverage is missing: "Codacy didn't receive a report"

**Pull request closed without merging**
